apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType }}
            backend:
              service:
                name: {{ include "nginx-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
