name: CI/CD Pipeline for NGINX App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v2

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            --push .

  helm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Determine Helm Chart Version
        id: get_version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "version=1.0.0" >> $GITHUB_ENV
          fi

      - name: Package Helm Chart
        run: helm package nginx-app --version ${{ env.version }}

      - name: Push Helm Chart to GitHub Pages (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          mv nginx-app-*.tgz docs/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Publishing Helm chart for version ${{ env.version }}" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main

  deploy:
    runs-on: ubuntu-latest
    needs: helm

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_KEY_JSON }}

      - name: Configure kubectl for GKE
        run: |
          # Extract project_id, and define cluster name and zone manually
          export PROJECT_ID=$(jq -r '.project_id' <<< "${{ secrets.GKE_KEY_JSON }}")
          export ZONE="YOUR_ZONE"                # Replace with your actual GKE cluster zone
          export CLUSTER_NAME="YOUR_CLUSTER_NAME" # Replace with your actual GKE cluster name

          # Authenticate kubectl to the GKE cluster
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Deploy Helm Chart
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          helm upgrade --install nginx-app ./nginx-app \
            --namespace ingress \
            --create-namespace \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ env.version }}
