name: CI/CD Pipeline for NGINX App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v3

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            --push .

  helm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Determine Helm Chart Version
        id: get_version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "version=1.0.0" >> $GITHUB_ENV
          fi

      - name: Package Helm Chart
        run: helm package nginx-app --version ${{ env.version }}

      - name: Push Helm Chart to GitHub Pages (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          mv nginx-app-*.tgz docs/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Publishing Helm chart for version ${{ env.version }}" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main

  deploy:
    runs-on: ubuntu-latest
    needs: helm
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_KEY_JSON }}

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Set Version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "version=1.0.0" >> $GITHUB_ENV
          fi

      - name: Deploy Helm Chart
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
          KUBECONFIG: /tmp/kubeconfig
        run: |
          helm upgrade --install nginx-app ./nginx-app \
            --namespace ingress \
            --create-namespace \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ env.version }}