name: CI/CD Pipeline for NGINX App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v3

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            --push .

  helm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Determine Helm Chart Version
        id: get_version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "version=1.0.0" >> $GITHUB_ENV
          fi

      - name: Package Helm Chart
        run: helm package nginx-app --version ${{ env.version }}

      - name: Push Helm Chart to GitHub Pages (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          mv nginx-app-*.tgz docs/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Publishing Helm chart for version ${{ env.version }}" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main

  deploy:
    runs-on: ubuntu-latest
    needs: helm

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_KEY_JSON }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true
          install_components: gke-gcloud-auth-plugin

      - name: Set USE_GKE_GCLOUD_AUTH_PLUGIN Environment Variable
        run: echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Configure kubectl for GKE
        run: |
          gcloud container clusters get-credentials "${{ secrets.GKE_CLUSTER }}" \
            --zone "${{ secrets.GKE_ZONE }}" \
            --project "${{ secrets.GKE_PROJECT }}"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
          version: ${{ env.version }}
        run: |
          helm upgrade --install nginx-app ./nginx-app \
            --namespace ingress \
            --create-namespace \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=$version
