name: CI Pipeline for NGINX App

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v2

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            --push .

  helm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Helm Chart
        run: helm package nginx-app --version ${{ github.ref_name }}

      - name: Push Helm Chart to GitHub Pages (optional)
        # Only if you're using GitHub Pages for Helm chart hosting
        run: |
          # Example step for deploying Helm charts to GitHub Pages
          mkdir -p docs
          mv nginx-app-*.tgz docs/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Publishing Helm chart for version ${{ github.ref_name }}"
          git push origin main
